### ISSUE TITLE
Improve UI when loading manifests.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/authn.io#101]
# Summary

The user interface blocks when trying to load hints from manifests.  This can result in a totally unresponsive UI with no feedback when one or more wallet sites are down.

# Steps to Reproduce

- If you have old wallet site info in your browser for live or test sites, you may already see this.
- If you need a test wallet that causes the issue:
  - Download https://github.com/digitalbazaar/chapi-demo-wallet
  - Pick some unused port and start the server: `./node_modules/.bin/http-server . -S --cors -p 8090`
  - Register a wallet.
  - Shut the server down.
- Now try the https://github.com/digitalbazaar/chapi-demo-issuer

Currently working wallets will have their manifests loaded.  But the request to the now offline site will block everything until a timeout is hit.

You may have to adjust `CACHE_TTL` in `components/manifest.js` or otherwise add some hacks to avoid caching while testing.

# Thoughts

At least one of the problems is in `Manifest.vue` `nextWizardStep` that calls `await this.loadHints()`.  This then calls `manifest.js` `getWebAppManfiest()`.  The manifests are loaded in parallel, but any request could block and then block the whole process before the UI is shown.

One approach would be to start the hint loading.  If content is cached, or loaded quickly, do what it does now and just have a short wait.  But if anything blocks for more than, say, 500ms or so then display the UI and let those loading calls proceed in the background.  If the UI is advanced before the loads are finished, then abort them.  Put up default UI hints or spinners as needed while background loading is happening.  And if errors happen, put up some indication of that in the UI.

**Comment by dlongley** [comment]
My suggestion is that the fix will involve creating a new primitive (or reusing an existing one if we have a match). This would be some kind of abstraction that represents a thing that is loading hints / web app manifests that can display a spinner if it's taking too long to load and expose a `loading` state to prevent it from being selected when it's loading. Then we can let the browser handle parallelizing fetching hints / web app manifests, etc.

**Comment by dlongley** [comment]
We should do a temporary fix that shows the UI immediately with a loading screen -- and then sets a short timeout for fetching each manifest. Then we can add a better fix later.

**Comment by dlongley** [comment]
This has been fixed in version 2.0.0: https://github.com/digitalbazaar/authn.io/commit/9e011378e714313eff1b1c397c736ea886a377d7
