### ISSUE TITLE
UX problem: Wallet registration UI mimics 'Allow Notification' too closely

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/authn.io#80]
The wallet registration UI ("[origin] wants to: Manage credentials"):

![Screen Shot 2020-05-02 at 7 26 36 PM](https://user-images.githubusercontent.com/947005/86367443-f5299900-bc49-11ea-8f66-28a8afce1976.png)

is too similar to the 'Allow notification UI':

![Screen Shot 2020-05-18 at 9 47 21 AM](https://user-images.githubusercontent.com/947005/86367525-1094a400-bc4a-11ea-92aa-5f038d8e051d.png)

Which was probably the original intention. However, usability tests show that since users have been trained to reflexively click 'Block' to Allow notification popups, they close the 'Manage credentials' popup without looking at it. (And then are confused about why they don't have a wallet.)

**Proposal:**

1. We update the registration UI to a much larger window, centered (vs its current 'tooltip' appearance).
2. Also make re-trying registration easier (in case the user closed the window by accident).

**Comment by dlongley** [comment]
> 1. We update the registration UI to a much larger window, centered (vs its current 'tooltip' appearance).

Can you be more specific about what you'd like to see? Perhaps a mock up?

> 2. Also make re-trying registration easier (in case the user closed the window by accident).

So this is up to the credential handler website. They can call registration (given a user interaction) as many times as they like -- though doing it in a way that may annoy users could be detected and force it to be silenced.

**Comment by dmitrizagidulin** [comment]
@dlongley np, will add mockup.

**Comment by dlongley** [comment]
Closing as addressed by #105. If the changes in #105 are still found to be insufficient, we can re-open/open a new issue.
