### ISSUE TITLE
JIT Onboarding: redirectUri parameter to CHAPI requests

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/authn.io#82]
(add on to the [JIT Onboarding/suggestedWallet](https://github.com/digitalbazaar/authorization.io/issues/81) issue)

In order to support a very common use case, where users first encounter a CHAPI UI button (such as 'Receive Credential' or 'Authenticate') _without_ having a wallet, we need to support the workflow where the user:

1. Encounters a CHAPI `get()` or `store()` event. 
2. The UI tells them they don't have any wallets registered, and suggests some.
3. User clicks on that wallet provider to register for a new wallet.

Since that last step is likely to take the user away from the original application they were on (especially if wallet login involves an email link), we need to provide a way to get the user back to the original requesting app (after registration).

This would be functionality similar to the OAuth2 / OIDC `redirect_uri` component.

Proposal:

```js
    const credentialQuery = {
      web: {
        VerifiablePresentation: {
          query: { ... },
          challenge: '3182bdea-63d9-11ea-b6de-3b7c1404d57f',
          domain: 'jobs.example.com',
          redirectUri: 'requesting-app.example.com'
        }
      }
    };
    const webCredential = await navigator.credentials.get(credentialQuery);
```

**Comment by dlongley** [comment]
Closing as this flow isn't needed -- JIT keeps the user in the flow they were in. If an email link is required, the wallet can use a ServiceWorker to get the user back to the window where the flow was happening.
